### PR TITLE
Add custom command names, typesafety, and error handling

### PR DESCRIPTION
**Pull request by joaomendoncaa**
## Motive

Sorry for the randomness, but I'm learning about lua's ecosystem because of neovim, and after stumbling upon this plugin (which is great, thank you for it) I decided it was a good idea to make a small change I personally wanted (add custom commands).

**Sadly, I ended up making quite the big change around, added some structure and types to the codebase.**

> ⚠️  I totally understand if you don't want these changes merged, in that case I'll just stick to using my fork. In the case you want some changes made to this PR feel free to request anything, happy to help.

### Additions

- Changed `search_engines` to typesafe `engines`
image
- Added `command_search`, `command_search_wiki`, `command_search_visual` config options so that the user can have custom command names
image

### CODE REVIEW

**Comment by joaomendoncaa** [comment]
A few comments that I just realized about after switching context:

1. We might not support Windows because of `core::get_os()` and `core.open_url()`. I didn't test it, but if that's the case; we can either a) fix it or b) add a warning to the `README.md` about not supporting windows.

2. We should change `WitSearch` to support grabbing the selected range and use it instead of having a separate api for `WitSearchVisual`. It would be more intuitive imo.

Let me know what you think.

**Comment by Aliqyan-21** [comment]
Hey I like the changes you did, they are really so good, I didn't knew we can use lua like this...I got to learn so much.

I will definitely commit it, just a after I have studied it a little more.

Great Work @joaomendoncaa!

**Comment by joaomendoncaa** [comment]
> Hey I like the changes you did, they are really so good, I didn't knew we can use lua like this...I got to learn so much.
> 
> I will definitely commit it, just a after I have studied it a little more.
> 
> Great Work @joaomendoncaa!

Awesome, glad you're open to improvements. 

I tried to add windows support but in the little time I had it proved to be more challenging than I was expecting, so I just defaulted to an error log on windows in case `core.open_url()` is called.

Let me know if you can think of any missing change/improvement, cheers.

**Comment by Aliqyan-21** [comment]
Hey @joaomendoncaa I am merging this commit I like it.

**Pull request merged**
